version: '3.8'
services:
  app:
    build: .
    image: clr_doc
    container_name: clearance
    volumes:
      - .:/app
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
