# Generated by Django 4.2 on 2024-04-13 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_studentaccount_ip_address_studentaccount_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminaccount',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
