# Generated by Django 4.2 on 2024-04-17 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_adminaccount_last_seen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminaccount',
            name='user_type',
            field=models.CharField(choices=[('principal', 'Principal'), ('academic', 'Academic Section'), ('cashier', 'Cash Section'), ('general', 'General Admin User')], default='general', max_length=10),
        ),
    ]
