# Generated by Django 4.2 on 2024-04-20 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_adminaccount_dept'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentaccount',
            name='ip_address',
        ),
        migrations.AddField(
            model_name='studentaccount',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
