# Generated by Django 4.2 on 2024-04-20 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_studentaccount_ip_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentaccount',
            name='registration',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
