# Generated by Django 4.2 on 2024-04-27 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_studentaccount_hall'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminaccount',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
