# Generated by Django 4.2 on 2024-05-03 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clearance', '0010_alter_department_dept_type'),
        ('accounts', '0010_adminaccount_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentPlaceholder',
            fields=[
                ('registration', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clearance.session')),
            ],
            options={
                'ordering': ['registration'],
            },
        ),
    ]
