# Generated by Django 4.2 on 2024-04-06 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clearance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_approved', models.BooleanField(default=False)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.studentaccount')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codename', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('display_name', models.CharField(max_length=50)),
                ('dept_type', models.CharField(choices=[('academic', 'Academic Dept'), ('accessory', 'Accessory Dept'), ('administrative', 'Administrative')], max_length=50)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('clerk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clerk', to='accounts.adminaccount')),
                ('head', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.adminaccount')),
            ],
        ),
        migrations.CreateModel(
            name='DeptApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_approved', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.adminaccount')),
                ('clearance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clearance.clearance')),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clearance.department')),
            ],
        ),
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codename', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clearance.department')),
                ('incharge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.adminaccount')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_year', models.IntegerField()),
                ('to_year', models.IntegerField()),
                ('batch_no', models.IntegerField()),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clearance.department')),
            ],
            options={
                'ordering': ['-from_year'],
            },
        ),
        migrations.CreateModel(
            name='LabApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_approved', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('owed', models.IntegerField(default=0)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.adminaccount')),
                ('clearance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clearance.clearance')),
                ('dept_approval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clearance.deptapproval')),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clearance.lab')),
            ],
        ),
        migrations.CreateModel(
            name='ClerkApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_approved', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('owed', models.IntegerField(default=0)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.adminaccount')),
                ('clearance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clearance.clearance')),
                ('dept_approval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clearance.deptapproval')),
            ],
        ),
        migrations.CreateModel(
            name='AdministrativeApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_approved', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('admin_role', models.CharField(choices=[('principal', 'Principal'), ('academic', 'SEC Academic'), ('cashier', 'Cashier')], max_length=50)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.adminaccount')),
                ('clearance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clearance.clearance')),
            ],
        ),
        migrations.AddConstraint(
            model_name='session',
            constraint=models.UniqueConstraint(fields=('from_year', 'dept'), name='unique_dept_session'),
        ),
        migrations.AddConstraint(
            model_name='session',
            constraint=models.UniqueConstraint(fields=('batch_no', 'dept'), name='unique_dept_batch'),
        ),
        migrations.AddConstraint(
            model_name='labapproval',
            constraint=models.UniqueConstraint(fields=('lab', 'clearance'), name='unique_lab_approval_per_clearance'),
        ),
        migrations.AddConstraint(
            model_name='deptapproval',
            constraint=models.UniqueConstraint(fields=('dept', 'clearance'), name='unique_dept_approval_per_clearance'),
        ),
        migrations.AddConstraint(
            model_name='clerkapproval',
            constraint=models.UniqueConstraint(fields=('dept_approval', 'clearance'), name='unique_clerk_approval_per_clearance'),
        ),
        migrations.AddConstraint(
            model_name='administrativeapproval',
            constraint=models.UniqueConstraint(fields=('clearance', 'admin_role'), name='unique_adminrole_per_clearance'),
        ),
    ]
