# Generated by Django 4.2 on 2024-04-10 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clearance', '0002_alter_department_codename_alter_lab_codename'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='administrativeapproval',
            options={'ordering': ['clearance__added_at']},
        ),
        migrations.AlterModelOptions(
            name='clerkapproval',
            options={'ordering': ['clearance__added_at']},
        ),
        migrations.AlterModelOptions(
            name='deptapproval',
            options={'ordering': ['clearance__added_at']},
        ),
        migrations.AlterModelOptions(
            name='labapproval',
            options={'ordering': ['clearance__added_at']},
        ),
        migrations.AddField(
            model_name='administrativeapproval',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clerkapproval',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deptapproval',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='labapproval',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
