# Generated by Django 4.2 on 2024-04-10 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clearance', '0003_alter_administrativeapproval_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clearance',
            name='progress',
            field=models.FloatField(default=0),
        ),
    ]
