# Generated by Django 4.2 on 2024-04-17 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clearance', '0006_administrativeapproval_remarks_added_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrativeapproval',
            name='admin_role',
            field=models.CharField(choices=[('principal', 'Principal'), ('academic', 'Academic Section'), ('cashier', 'Cash Section')], max_length=50),
        ),
    ]
