# Generated by Django 4.2 on 2024-04-20 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clearance', '0007_alter_administrativeapproval_admin_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['-id']},
        ),
    ]
