# Generated by Django 4.2 on 2024-04-23 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clearance', '0009_alter_department_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='dept_type',
            field=models.CharField(choices=[('academic', 'Academic Dept'), ('accessory', 'Accessory Dept'), ('hall', 'Residential Hall'), ('administrative', 'Administrative')], max_length=50),
        ),
    ]
